### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wilddylan** [Urinx/iOSAppHook#18]
在iOS10.1.1上 运行加入dylib后重新签名的App后，会闪退。
如果不加入dylib，则没有问题。
出现这个问题的原因可能是什么呢？希望得到解答。

**Comment by levicn** [comment]
Same to you.
Just resign the app is successful,
with the dylib will crash.

**Comment by keshiim** [comment]
删除watchkit

**Comment by levicn** [comment]
I have resovled the problem,
delete the folder of Watch and Plugins.

**Comment by wilddylan** [comment]
解决了，谢谢。
