### ISSUE TITLE
重签名 显示名称不可用. URL types 不可改?

### ISSUE THREAD

**Issue by zackhsuan** [Urinx/iOSAppHook#2]
非常感谢这篇Wiki和AppResign 非常好用!

不过有几个问题, 一个就是设置的Display Name似乎是没有啥用处. 
然后我发现冲签名的微信URL types会覆盖掉原来的微信. 就是跳转或分享的时候 跳到了新的微信 而不是旧的 这个有没有办法呢

**Comment by Urinx** [comment]
@zackhsuan Display Name一般默认即可。对于重名的scheme，默认是新安装的应用优先级较高，所以就会造成了scheme劫持，如果影响到原来的微信的话我建议直接修改info.plist里的URL types就可以了。

**Comment by zackhsuan** [comment]
@Urinx 我改了... 但是完了AppResign冲签名按照之后 不起作用... Info.plist的会不会已经编译过了的

**Comment by Urinx** [comment]
@zackhsuan 不会啊 😮  我修改后是没有问题的

**Comment by zackhsuan** [comment]
是重签名之前改 然后重签名? 还是重签名之后改呢

**Comment by Urinx** [comment]
@zackhsuan 我是在签名前改的

**Comment by zackhsuan** [comment]
额... 我要疯了 我也是这样的... 我在签名之前 改了plist里面的URL Types了 然后签名重装, 其他app点击分享 还是跳转的新的微信...
