### ISSUE TITLE
大神求帮助关于AppResign

### ISSUE THREAD

**Issue by chenfengfeng** [Urinx/iOSAppHook#4]
在Release下载了2.0版本
是否将AppResign放在username下的文件夹下面?
我输入后提示:-bash: ./AppResign: Permission denied
是不是操作错误呢?

**Comment by Urinx** [comment]
放在你终端当前所在的目录下就可以了，这个 Permission denied 因为访问某些路径和文件有可能需要root权限，sudo执行

**Comment by chenfengfeng** [comment]
呃~我应该没下载错误吧,我下载的是AppResign(8.7M),我放在下载文件夹,但是用命令行执行提示-bash: AppResign: command not found

**Comment by Urinx** [comment]
那你就`cd Downloads`文件夹再执行啊

**Comment by chenfengfeng** [comment]
本来就是cd到Downloads文件夹执行的~

**Comment by Urinx** [comment]
那就没有问题啊。。。

**Comment by chenfengfeng** [comment]
但还是会提示找不到= =!比较郁闷

**Comment by chenzhijie** [comment]
@chenfengfeng `chmod +x AppResign`
